name: Create Release

on:
  pull_request

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Create Release
      id: create_release
      uses: zendesk/action-create-release@v1
      env:
        GITHUB_TOKEN: ${{ github.token  }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body: |
          Changes in this Release
          - First Change
          - Second Change
        draft: false
        prerelease: false
