name: Notify Telegram

on:
  push:
    branches: [ main ]
#    pull_request:
#      types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:     
      - uses: actions/checkout@v2
      - uses: 8BitJonny/gh-get-current-pr@v1
        id: PR
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get branch name
        run: |
          echo "BRANCH_NAME=$(echo $pr | jq '.head.ref' | sed 's/"//g')" >> $GITHUB_ENV
        env:
          pr: ${{ steps.get-pull-request.outputs.pr }}

      - name: Echo branch
        run: |
          echo $BRANCH_NAME \
          echo "${prNumber} "
        env:
          prNumber: ${{ steps.PR.outputs.number }}
#       - uses: actions/checkout@master
#       - name: Send message telegram
#         uses: appleboy/telegram-action@master
#         with:
#           to: ${{ secrets.TELEGRAM_TO }}
#           token: ${{ secrets.TELEGRAM_TOKEN }}
#           message: |
#             New pull request in the repository chatbot-telegram by the user: ${{ env.PR_USER }}
#             pull request: ${{ env.PR_URL }}
