name: Notify Telegram

on:
  push:
    branches: [ main ]

jobs:
  up:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: 8BitJonny/gh-get-current-pr@1.0.1
        id: get-pull-request
        with:
          github-token: ${{ github.token }}

      - name: Get branch name
        run: |
          echo "BRANCH_NAME=$(echo $pr | jq '.head.ref' | sed 's/"//g')" >> $GITHUB_ENV
        env:
          pr: ${{ steps.get-pull-request.outputs.pr }}

      - name: Echo branch
        run: |
          echo $BRANCH_NAME
      - name: Validates stack according to branch name
        run: |
          if [[ "$BRANCH_NAME" == *"prod-virginia"* ]]; then
              echo "STACK=$(echo prod-virginia)" >> $GITHUB_ENV
          elif [[ "$BRANCH_NAME" == *"prod-ohio"* ]]; then
              echo "STACK=$(echo prod-ohio)" >> $GITHUB_ENV
          else
              echo There is no production account in this pull request
          fi

#       - uses: actions/checkout@master
#       - name: Send message telegram
#         uses: appleboy/telegram-action@master
#         with:
#           to: ${{ secrets.TELEGRAM_TO }}
#           token: ${{ secrets.TELEGRAM_TOKEN }}
#           message: |
#             New pull request in the repository chatbot-telegram by the user: ${{ env.PR_USER }}
#             pull request: ${{ env.PR_URL }}
