name: Notify new pr

on:
  pull_request:
    types: [opened]

jobs:
  notify-new-pr:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Python Linter
        uses: sunnysid3up/python-linter@master
        with:
          source: "src"
          mypy-options: "--ignore-missing-imports --show-error-codes"
          pylint-options: "--rcfile=.pylintrc"

      - uses: actions/checkout@master
      - name: Send message telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            New pull request #${{ github.event.number }} in the novato-dev repository by the user: ${{ github.event.pull_request.user.login }}
