name: Notify merged

on:
  pull_request:
    types: [closed]

jobs:
  notify-merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
     
    - uses: 8BitJonny/gh-get-current-pr@1.0.1
      id: get-pull-request
      with:
        github-token: ${{ github.token }}
    
    - name: Get info of pull request
      run: |
        echo "PR_NUMBER=$(echo $pr | jq '.number')" >> $GITHUB_ENV \
        && echo "PR_USER=$(echo $pr | jq '.user.login'| sed 's/"//g')" >> $GITHUB_ENV \
        && echo "PR_URL=$(echo $pr | jq '.html_url' | sed 's/"//g')" >> $GITHUB_ENV
      env:
        pr: ${{ steps.get-pull-request.outputs.pr }}
        
    - uses: actions/checkout@master
    - name: Send message telegram
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          Merged pull request #${{ env.PR_NUMBER }} in the chatbot-telegram repository by the user: ${{ env.PR_USER }}
          pull request: ${{ env.PR_URL }}
