name: Notify Telegram

on:
  pull_request
#     types: [opened]

jobs:
  up:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      
      - uses: kceb/pull-request-url-action@v1
        id: pr-url

      - run: echo "${{ steps.pr-url.outputs.url }}"

#       - uses: actions/checkout@master
#       - name: Send message telegram
#         uses: appleboy/telegram-action@master
#         with:
#           to: ${{ secrets.TELEGRAM_TO }}
#           token: ${{ secrets.TELEGRAM_TOKEN }}
#           message: |
#             New pull request ${{ github.event.number }} in the repository chatbot-telegram by the user: LucasRejanio
#             pull request: teste
