# name: Open pull request

# on:
#   pull_request:
#     types: [opened]

# jobs:
#   open-pull-request:
#     runs-on: ubuntu-20.04

#     steps:
#       - uses: actions/checkout@v2

#       - uses: actions/checkout@master
#       - name: Send message telegram
#         uses: appleboy/telegram-action@master
#         with:
#           to: ${{ secrets.TELEGRAM_TO }}
#           token: ${{ secrets.TELEGRAM_TOKEN }}
#           message: |
#             New pull request #${{ github.event.number }} in the novato-dev repository by the user: ${{ github.event.pull_request.user.login }}
