name: Open pull request

on:
  pull_request:
    types: [opened]

jobs:
  open-pull-request:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@master
      - name: Send message telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Um novo pull request #${{ github.event.number }} foi aberto no repositório do novato-dev pelo usuário: ${{ github.event.pull_request.user.login }}.
            Quando tiver um tempinho corre lá pra fazer aquele famoso code review. Tenho certeza que vai gostar!

      - uses: actions/github-script@v3
        if: contains(github.head_ref, 'release-')
        with:
          github-token: ${{ github.token }}
          script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['release']
            })
