name: Pylint

on:
  pull_request

jobs:
  pylint:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run pylint
        run: |
          find ./ -type f -name "*.py" -not -path "./venv/*" | xargs pylint
